[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "MonoDetour"
name = "MonoDetour_BepInEx_5"
description = "Integrates MonoDetour's logger with BepInEx and as a side effect initializes MonoDetour early. MonoDetour is an easy and convenient .NET detouring library, powered by MonoMod.RuntimeDetour."
websiteUrl = "https://github.com/MonoDetour/MonoDetour"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
MonoDetour-MonoDetour = "__MonoDetour_Version__"

[build]
icon = "../../icon.png"
readme = "./README.md"
outdir = "../../artifacts/thunderstore/"

[[build.copy]]
source = "../../artifacts/bin/MonoDetour.BepInEx.5/release/0.com.github.MonoDetour.BepInEx.5.dll"
target = "patchers/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

[publish]
# https://thunderstore.io/api/experimental/community/
communities = [ "lethal-company", "repo", "riskofrain2" ]

[publish.categories]
# https://thunderstore.io/api/experimental/community/lethal-company/category/
lethal-company = [ "libraries", ]
repo = [ "libraries", ]
riskofrain2 = [ "libraries", ]
