[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "MonoDetour"
name = "MonoDetour_BepInEx_5"
description = "HarmonyX interop & BepInEx 5 logger integration for MonoDetour. Initializes MonoDetour early as a side effect."
websiteUrl = "https://github.com/MonoDetour/MonoDetour"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
MonoDetour-MonoDetour = "__MonoDetour_Version__"

[build]
icon = "../../icon.png"
readme = "./README.md"
outdir = "../../artifacts/thunderstore/"

[[build.copy]]
source = "../../artifacts/bin/MonoDetour.BepInEx.5/release/0.com.github.MonoDetour.BepInEx.5.dll"
target = "patchers/"

[[build.copy]]
source = "../../artifacts/bin/MonoDetour.Interop.HarmonyX/release/netstandard2.0/com.github.MonoDetour.Interop.HarmonyX.dll"
target = "patchers/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

[publish]
# https://thunderstore.io/api/experimental/community/
communities = [
    "lethal-company",
    "repo",
    "riskofrain2",
    "peak",
    "hollow-knight-silksong",
    "gloomwood"
]

[publish.categories]
# https://thunderstore.io/api/experimental/community/lethal-company/category/
lethal-company = [ "libraries", ]
repo = [ "libraries", ]
riskofrain2 = [ "libraries", ]
peak = [ "libraries", ]
hollow-knight-silksong = [ "libraries", ]
gloomwood = [ "libraries", ]
