[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "MonoDetour"
name = "MonoDetour_BepInEx_6"
description = "HarmonyX interop & BepInEx 6 logger integration for MonoDetour. Initializes MonoDetour early as a side effect."
websiteUrl = "https://github.com/MonoDetour/MonoDetour"
containsNsfwContent = false
[package.dependencies]
MonoDetour-MonoDetour = "__MonoDetour_Version__"

[build]
icon = "../../icon.png"
readme = "./README.md"
outdir = "../../artifacts/thunderstore/"

[[build.copy]]
source = "../../artifacts/bin/MonoDetour.BepInEx.6/release/0.com.github.MonoDetour.BepInEx.6.dll"
target = "patchers/"

[[build.copy]]
source = "../../artifacts/bin/MonoDetour.Interop.HarmonyX/release/netstandard2.0/com.github.MonoDetour.Interop.HarmonyX.dll"
target = "patchers/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

[publish]
# https://thunderstore.io/api/experimental/community/
communities = [
    "resonite",
]

[publish.categories]
# https://thunderstore.io/api/experimental/community/lethal-company/category/
resonite = [ "libraries", ]

